// ── Executive Board Report Generator ────────────────────────
// Generates a print-ready HTML report. User clicks "Save as PDF".
// Fully client-side. Accepts custom theme colors.

const fmt = n => n >= 1e6 ? `$${(n/1e6).toFixed(2)}M` : n >= 1e3 ? `$${(n/1e3).toFixed(0)}K` : `$${n}`;
const fmtFull = n => `$${Math.round(n).toLocaleString()}`;

// Default theme — overridable
const DEFAULT_THEME = {
  primary: '#3B82F6',
  secondary: '#8B5CF6',
  success: '#10B981',
  warning: '#F59E0B',
  danger: '#EF4444',
  ink: '#1A1A2E',
  sub: '#6B7280',
  faint: '#9CA3AF',
  line: '#E5E7EB',
  lineSoft: '#F3F4F6',
};

export function generateReport({ projects, pms, orgName = 'DeliverIQ', logoUrl = null, theme = {} }) {
  const T = { ...DEFAULT_THEME, ...theme };
  const hc = h => h >= 70 ? T.success : h >= 40 ? T.warning : T.danger;
  const sLabel = s => s === 'on-track' ? 'On Track' : s === 'at-risk' ? 'At Risk' : 'Critical';
  const sColor = s => s === 'on-track' ? T.success : s === 'at-risk' ? T.warning : T.danger;

  const P = [...projects];
  const totalRev = P.reduce((s, p) => s + p.rev, 0);
  const totalBilled = P.reduce((s, p) => s + p.billed, 0);
  const atRisk = P.filter(p => p.status !== 'on-track');
  const revAtRisk = atRisk.reduce((s, p) => s + (p.rev - p.billed), 0);
  const avgHealth = P.length ? Math.round(P.reduce((s, p) => s + p.health, 0) / P.length) : 0;
  const overdue = P.reduce((s, p) => s + p.ov, 0);
  const critical = P.filter(p => p.status === 'critical');
  const onTrack = P.filter(p => p.status === 'on-track');
  const billPct = totalRev > 0 ? Math.round(totalBilled / totalRev * 100) : 0;
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Regional breakdown
  const byRegion = {};
  P.forEach(p => {
    if (!byRegion[p.region]) byRegion[p.region] = { total: 0, billed: 0, count: 0, risk: 0 };
    byRegion[p.region].total += p.rev;
    byRegion[p.region].billed += p.billed;
    byRegion[p.region].count++;
    if (p.status !== 'on-track') byRegion[p.region].risk += (p.rev - p.billed);
  });
  const regions = Object.entries(byRegion).sort((a, b) => b[1].total - a[1].total);

  // Logo mark SVG (hexagon + chart) — inherits theme colors
  const logoMark = logoUrl
    ? `<img src="${logoUrl}" alt="" style="width:46px;height:46px;border-radius:11px;object-fit:cover"/>`
    : `<svg width="46" height="46" viewBox="0 0 64 64">
        <defs><linearGradient id="lg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${T.primary}"/><stop offset="1" stop-color="${T.secondary}"/></linearGradient></defs>
        <path d="M32 3 L52.8 15 L52.8 49 L32 61 L11.2 49 L11.2 15 Z" fill="url(#lg)"/>
        <path d="M20 40 L27 31 L34 36 L44 23" fill="none" stroke="#fff" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round"/>
        <circle cx="44" cy="23" r="3.2" fill="#fff"/><circle cx="20" cy="40" r="2.4" fill="#fff" opacity="0.7"/>
      </svg>`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${orgName} — Executive Delivery Report</title>
<style>
  @page {
    size: A4;
    margin: 13mm 14mm 17mm;
    @bottom-left {
      content: "Generated by ${orgName} · Confidential";
      font-family: 'Segoe UI', Arial, sans-serif; font-size: 8px; color: ${T.faint};
      border-top: 1px solid ${T.line}; padding-top: 5px; vertical-align: top;
    }
    @bottom-center {
      content: ""; border-top: 1px solid ${T.line}; padding-top: 5px;
    }
    @bottom-right {
      content: "${today} · Page " counter(page) " of " counter(pages);
      font-family: 'Segoe UI', Arial, sans-serif; font-size: 8px; color: ${T.faint};
      border-top: 1px solid ${T.line}; padding-top: 5px; vertical-align: top;
    }
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body { font-family: 'Segoe UI', -apple-system, Arial, sans-serif; color: ${T.ink}; line-height: 1.5; font-size: 11px; }
  .page-break { page-break-before: always; }
  tr, .no-break { page-break-inside: avoid; }

  /* ── Report shell: thead/tfoot repeat on every printed page ── */
  .report-shell { width: 100%; border-collapse: collapse; }
  .report-shell > thead { display: table-header-group; }
  .report-shell > tfoot { display: table-footer-group; }
  .report-shell > thead > tr > td,
  .report-shell > tfoot > tr > td,
  .report-shell > tbody > tr > td { padding: 0; }

  /* ── Letterhead (inside thead — repeats every page) ── */
  .letterhead { display: flex; justify-content: space-between; align-items: center; padding-bottom: 9px; border-bottom: 2.5px solid ${T.primary}; }
  .lh-left { display: flex; align-items: center; gap: 11px; }
  .lh-name { font-size: 17px; font-weight: 800; color: ${T.ink}; line-height: 1.05; }
  .lh-name .iq { color: ${T.primary}; }
  .lh-tag { font-size: 7px; font-weight: 700; letter-spacing: 1.8px; text-transform: uppercase; color: ${T.primary}; margin-top: 2px; }
  .lh-right { text-align: right; }
  .lh-title { font-size: 11px; font-weight: 700; color: ${T.ink}; }
  .lh-date { font-size: 8.5px; color: ${T.sub}; margin-top: 2px; }
  /* spacing band between letterhead and body, repeats each page */
  .lh-spacer { height: 16px; }

  /* ── Page footer (inside tfoot — repeats every page) ── */
  .page-footer { display: flex; justify-content: space-between; align-items: center; padding-top: 8px; border-top: 1px solid ${T.line}; font-size: 8px; color: ${T.faint}; }
  .pf-spacer { height: 12px; }

  /* ── Section titles ── */
  .section-title { font-size: 12px; font-weight: 700; color: ${T.ink}; margin: 24px 0 12px; padding-bottom: 7px; border-bottom: 1px solid ${T.line}; letter-spacing: 0.2px; }
  .body-top { margin-top: 22px; }

  /* ── Executive summary ── */
  .summary { background: ${T.primary}0D; border-left: 4px solid ${T.primary}; border-radius: 0 8px 8px 0; padding: 15px 18px; }
  .summary p { font-size: 11px; color: #374151; margin-bottom: 7px; }
  .summary p:last-child { margin-bottom: 0; }
  .summary strong { color: ${T.ink}; font-weight: 700; }

  /* ── KPI cards ── */
  .kpi-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 11px; }
  .kpi { border: 1px solid ${T.line}; border-radius: 11px; padding: 15px 16px; background: #FBFCFD; }
  .kpi-label { font-size: 8px; font-weight: 700; letter-spacing: 0.6px; text-transform: uppercase; color: ${T.faint}; }
  .kpi-value { font-size: 23px; font-weight: 800; margin: 6px 0 3px; line-height: 1; letter-spacing: -0.5px; }
  .kpi-sub { font-size: 9px; color: ${T.sub}; }

  /* ── Risk callout ── */
  .risk-box { background: ${T.danger}0D; border: 1px solid ${T.danger}33; border-radius: 9px; padding: 13px 16px; }
  .risk-title { font-size: 11px; font-weight: 700; color: ${T.danger}; margin-bottom: 8px; }
  .risk-item { font-size: 10px; color: #7F1D1D; padding: 4px 0; display: flex; justify-content: space-between; align-items: center; gap: 16px; border-top: 1px solid ${T.danger}1A; }
  .risk-item:first-of-type { border-top: none; padding-top: 0; }
  .risk-item .r-left { flex: 1; }
  .risk-item .r-right { white-space: nowrap; font-variant-numeric: tabular-nums; color: ${T.danger}; font-weight: 600; }

  /* ── Tables ── */
  table { width: 100%; border-collapse: collapse; table-layout: fixed; }
  th { text-align: left; font-size: 8px; font-weight: 700; letter-spacing: 0.5px; text-transform: uppercase; color: ${T.faint}; padding: 9px 10px; border-bottom: 2px solid ${T.line}; }
  td { padding: 10px; border-bottom: 1px solid ${T.lineSoft}; font-size: 10px; vertical-align: middle; }
  .proj-name { font-weight: 700; color: ${T.ink}; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .proj-client { font-size: 8px; color: ${T.faint}; margin-top: 1px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .status-pill { display: inline-block; padding: 3px 9px; border-radius: 10px; font-size: 8px; font-weight: 700; white-space: nowrap; }
  .num { font-variant-numeric: tabular-nums; font-weight: 600; }
  .col-r { text-align: right; }
  .col-c { text-align: center; }

  /* ── Regional bars ── */
  .region-row { margin-bottom: 14px; }
  .region-row:last-child { margin-bottom: 0; }
  .region-head { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 5px; }
  .region-name { font-size: 11px; font-weight: 700; color: ${T.ink}; }
  .region-name .rc { font-weight: 400; color: ${T.faint}; font-size: 9px; }
  .region-val { font-size: 12px; font-weight: 700; color: ${T.ink}; font-variant-numeric: tabular-nums; }
  .bar-track { height: 9px; background: ${T.line}; border-radius: 5px; overflow: hidden; display: flex; }
  .bar-billed { height: 100%; background: ${T.success}; }
  .bar-unbilled { height: 100%; background: ${T.primary}55; }
  .region-meta { font-size: 8px; color: ${T.sub}; margin-top: 4px; }

  /* ── PM cards ── */
  .pm-row { display: flex; align-items: center; gap: 13px; padding: 11px 14px; border: 1px solid ${T.line}; border-radius: 9px; margin-bottom: 7px; }
  .pm-row:last-child { margin-bottom: 0; }
  .pm-rank { font-size: 15px; width: 22px; text-align: center; flex-shrink: 0; }
  .pm-avatar { width: 36px; height: 36px; border-radius: 18px; display: flex; align-items: center; justify-content: center; color: #fff; font-size: 12px; font-weight: 800; flex-shrink: 0; }
  .pm-info { flex: 1; min-width: 0; }
  .pm-name { font-size: 11px; font-weight: 700; color: ${T.ink}; }
  .pm-region { font-size: 9px; color: ${T.faint}; margin-top: 1px; }
  .pm-stats { display: flex; gap: 18px; flex-shrink: 0; }
  .pm-stat { text-align: center; min-width: 38px; }
  .pm-stat-label { font-size: 7px; font-weight: 700; letter-spacing: 0.4px; text-transform: uppercase; color: ${T.faint}; }
  .pm-stat-val { font-size: 13px; font-weight: 800; margin-top: 2px; font-variant-numeric: tabular-nums; }

  /* ── Footer ── */
  .footer { margin-top: 26px; padding-top: 12px; border-top: 1px solid ${T.line}; display: flex; justify-content: space-between; font-size: 8px; color: ${T.faint}; }

  /* ── Print bar (screen only) ── */
  .print-bar { position: fixed; top: 0; left: 0; right: 0; background: #0F1729; padding: 12px 24px; display: flex; justify-content: space-between; align-items: center; z-index: 1000; box-shadow: 0 2px 12px rgba(0,0,0,0.3); }
  .print-bar span { color: #E8ECF4; font-size: 13px; font-weight: 600; }
  .print-btn { padding: 9px 22px; border-radius: 8px; border: none; background: linear-gradient(135deg, ${T.primary}, ${T.secondary}); color: #fff; font-size: 13px; font-weight: 700; cursor: pointer; }
  @media print {
    .print-bar { display: none !important; }
    .sheet { margin: 0 !important; box-shadow: none !important; max-width: none !important; padding: 0 !important; }
    body { background: #fff !important; }
  }
  @media screen {
    body { background: #E5E7EB; }
    .sheet { max-width: 800px; margin: 64px auto 40px; background: #fff; padding: 40px 44px; box-shadow: 0 4px 24px rgba(0,0,0,0.15); border-radius: 4px; }
  }
</style>
</head>
<body>
  <div class="print-bar">
    <span>${orgName} Executive Delivery Report — ${today}</span>
    <button class="print-btn" onclick="window.print()">Save as PDF</button>
  </div>

  <div class="sheet">
    <table class="report-shell">
    <thead>
      <tr><td>
        <!-- Letterhead — repeats on every page in print -->
        <div class="letterhead">
          <div class="lh-left">
            ${logoMark}
            <div>
              <div class="lh-name">${orgName === 'DeliverIQ' ? 'Deliver<span class="iq">IQ</span>' : orgName}</div>
              <div class="lh-tag">Delivery Intelligence Report</div>
            </div>
          </div>
          <div class="lh-right">
            <div class="lh-title">Executive Portfolio Summary</div>
            <div class="lh-date">${today} · ${P.length} Active Projects</div>
          </div>
        </div>
        <div class="lh-spacer"></div>
      </td></tr>
    </thead>
    <tfoot>
      <tr><td><div class="pf-spacer"></div></td></tr>
    </tfoot>
    <tbody>
      <tr><td>
    <!-- Executive Summary -->
    <div class="section-title" style="margin-top:0">Executive Summary</div>
    <div class="summary no-break">
      <p>The portfolio comprises <strong>${P.length} active projects</strong> with a total contract value of <strong>${fmtFull(totalRev)}</strong>, of which <strong>${fmtFull(totalBilled)} (${billPct}%)</strong> has been billed to date.</p>
      <p><strong>${onTrack.length} projects</strong> are on track, while <strong>${atRisk.length}</strong> require attention${critical.length > 0 ? `, including <strong style="color:${T.danger}">${critical.length} in critical status</strong>` : ''}. Total revenue at risk stands at <strong style="color:${T.danger}">${fmtFull(revAtRisk)}</strong>.</p>
      <p>There ${overdue === 1 ? 'is' : 'are'} currently <strong>${overdue} overdue milestone${overdue === 1 ? '' : 's'}</strong> across the portfolio. Average portfolio health is <strong style="color:${hc(avgHealth)}">${avgHealth}%</strong>.</p>
    </div>

    <!-- KPIs -->
    <div class="section-title">Key Metrics</div>
    <div class="kpi-grid no-break">
      <div class="kpi"><div class="kpi-label">Portfolio Value</div><div class="kpi-value" style="color:${T.ink}">${fmt(totalRev)}</div><div class="kpi-sub">${billPct}% billed</div></div>
      <div class="kpi"><div class="kpi-label">Revenue at Risk</div><div class="kpi-value" style="color:${T.danger}">${fmt(revAtRisk)}</div><div class="kpi-sub">${atRisk.length} projects off-track</div></div>
      <div class="kpi"><div class="kpi-label">Avg Health</div><div class="kpi-value" style="color:${hc(avgHealth)}">${avgHealth}%</div><div class="kpi-sub">${onTrack.length} on track</div></div>
      <div class="kpi"><div class="kpi-label">Overdue Milestones</div><div class="kpi-value" style="color:${overdue > 0 ? T.danger : T.success}">${overdue}</div><div class="kpi-sub">requiring action</div></div>
    </div>

    ${critical.length > 0 ? `
    <div class="section-title">Immediate Attention Required</div>
    <div class="risk-box no-break">
      <div class="risk-title">${critical.length} Critical Project${critical.length > 1 ? 's' : ''}</div>
      ${critical.map(p => `
        <div class="risk-item">
          <span class="r-left"><strong>${p.name}</strong> &nbsp;·&nbsp; ${p.client} &nbsp;·&nbsp; Health ${p.health}%</span>
          <span class="r-right">${p.ov} overdue · ${p.dd}d behind · ${fmt(p.rev - p.billed)} unbilled</span>
        </div>
      `).join('')}
    </div>
    ` : ''}

    <div class="page-break"></div>

    <!-- Project Table -->
    <div class="section-title">Portfolio Detail</div>
    <table>
      <colgroup>
        <col style="width:27%"><col style="width:15%"><col style="width:12%">
        <col style="width:11%"><col style="width:13%"><col style="width:12%"><col style="width:10%">
      </colgroup>
      <thead>
        <tr>
          <th>Project</th><th>Project Manager</th><th>Status</th>
          <th class="col-c">Health</th><th class="col-r">Value</th><th class="col-r">Billed</th><th class="col-c">Overdue</th>
        </tr>
      </thead>
      <tbody>
        ${P.sort((a, b) => a.health - b.health).map(p => {
          const bp = p.rev > 0 ? Math.round(p.billed / p.rev * 100) : 0;
          return `
          <tr>
            <td><div class="proj-name">${p.name}</div><div class="proj-client">${p.client} · ${p.region}</div></td>
            <td style="font-size:9px;color:${T.sub}">${p.pm}</td>
            <td><span class="status-pill" style="color:${sColor(p.status)};background:${sColor(p.status)}1A">${sLabel(p.status)}</span></td>
            <td class="col-c"><span class="num" style="color:${hc(p.health)}">${p.health}%</span></td>
            <td class="col-r num">${fmt(p.rev)}</td>
            <td class="col-r"><span class="num" style="color:${bp > 70 ? T.success : bp > 30 ? T.warning : T.danger}">${bp}%</span></td>
            <td class="col-c">${p.ov > 0 ? `<span class="num" style="color:${T.danger}">${p.ov}</span>` : `<span style="color:${T.success}">—</span>`}</td>
          </tr>`;
        }).join('')}
      </tbody>
    </table>

    <!-- Regional Revenue -->
    <div class="section-title">Revenue by Region</div>
    <div class="no-break">
    ${regions.map(([region, d]) => {
      const billedPct = d.total > 0 ? (d.billed / d.total) * 100 : 0;
      const unbilledPct = d.total > 0 ? ((d.total - d.billed) / d.total) * 100 : 0;
      return `
      <div class="region-row">
        <div class="region-head">
          <span class="region-name">${region} <span class="rc">· ${d.count} project${d.count > 1 ? 's' : ''}</span></span>
          <span class="region-val">${fmtFull(d.total)}</span>
        </div>
        <div class="bar-track"><div class="bar-billed" style="width:${billedPct}%"></div><div class="bar-unbilled" style="width:${unbilledPct}%"></div></div>
        <div class="region-meta">Billed ${fmtFull(d.billed)} · Remaining ${fmtFull(d.total - d.billed)}${d.risk > 0 ? ` · At risk ${fmtFull(d.risk)}` : ''}</div>
      </div>`;
    }).join('')}
    </div>

    ${pms && pms.length > 0 ? `
    <div class="section-title">Team Performance</div>
    <div class="no-break">
    ${pms.slice(0, 5).map((pm, i) => {
      const grads = [`linear-gradient(135deg,${T.success},#059669)`, `linear-gradient(135deg,${T.primary},#2563EB)`, `linear-gradient(135deg,${T.secondary},#7C3AED)`, `linear-gradient(135deg,${T.warning},#D97706)`, `linear-gradient(135deg,${T.danger},#DC2626)`];
      const medal = ['1st', '2nd', '3rd'][i] || `${i + 1}th`;
      return `
      <div class="pm-row">
        <div class="pm-rank" style="color:${T.faint}">${medal}</div>
        <div class="pm-avatar" style="background:${grads[i % 5]}">${pm.ini}</div>
        <div class="pm-info">
          <div class="pm-name">${pm.name}</div>
          <div class="pm-region">${pm.region} · ${pm.xp.toLocaleString()} XP${pm.streak > 0 ? ` · ${pm.streak}wk streak` : ''}</div>
        </div>
        <div class="pm-stats">
          <div class="pm-stat"><div class="pm-stat-label">Health</div><div class="pm-stat-val" style="color:${hc(Math.round(pm.ah))}">${Math.round(pm.ah)}%</div></div>
          <div class="pm-stat"><div class="pm-stat-label">Billing</div><div class="pm-stat-val" style="color:${pm.br >= 0.7 ? T.success : pm.br >= 0.4 ? T.warning : T.danger}">${Math.round(pm.br * 100)}%</div></div>
          <div class="pm-stat"><div class="pm-stat-label">Overdue</div><div class="pm-stat-val" style="color:${pm.ov === 0 ? T.success : T.danger}">${pm.ov === 0 ? '0' : pm.ov}</div></div>
        </div>
      </div>`;
    }).join('')}
    </div>
    ` : ''}
      </td></tr>
    </tbody>
    </table>
  </div>

  <script>window.focus();</script>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (win) { win.document.write(html); win.document.close(); }
  else { alert('Please allow pop-ups to generate the report.'); }
  return html;
}
