import { useState, useEffect, useRef } from 'react';
import { parseCSV, transformToProjects } from './lib/csvParser';
import { saveProjects, savePMs, loadAll, hasData, clearAll, SAMPLE_PROJECTS, SAMPLE_PMS } from './lib/store';
import { generateReport } from './lib/reportGenerator';

const C={bg:"#080E1A",sf:"#0F1729",cd:"#131D35",bd:"#1E2A45",bh:"#2A3A5C",tx:"#E8ECF4",sb:"#7B8BA8",dm:"#4A5A78",ac:"#3B82F6",pp:"#8B5CF6",gn:"#10B981",am:"#F59E0B",rd:"#EF4444"};
const G=`linear-gradient(135deg,${C.ac},${C.pp})`;
const hc=h=>h>=70?C.gn:h>=40?C.am:C.rd;
const sc=s=>s==="on-track"?C.gn:s==="at-risk"?C.am:C.rd;
const fmt=n=>n>=1e6?`$${(n/1e6).toFixed(1)}M`:n>=1e3?`$${(n/1e3).toFixed(0)}K`:`$${n}`;
const BADGES={perfectBilling:{i:"💰",n:"Cash Machine"},zeroOverdue:{i:"⏱️",n:"Clockwork"},streakMaster:{i:"🔥",n:"On Fire"},topHealth:{i:"💚",n:"Green Giant"},fastCloser:{i:"⚡",n:"Speed Demon"},teamPlayer:{i:"🤝",n:"Team Player"}};
const LEVELS=[{n:"Rookie",m:0,i:"🌱",c:"#7B8BA8"},{n:"Bronze",m:500,i:"🥉",c:"#CD7F32"},{n:"Silver",m:1200,i:"🥈",c:"#A8B5C8"},{n:"Gold",m:2200,i:"🥇",c:"#FFD700"},{n:"Platinum",m:3500,i:"💎",c:"#7DD3FC"},{n:"Diamond",m:5000,i:"👑",c:"#C084FC"}];
const gLv=xp=>{for(let i=LEVELS.length-1;i>=0;i--)if(xp>=LEVELS[i].m)return{...LEVELS[i],nx:LEVELS[i+1]||null};return{...LEVELS[0],nx:LEVELS[1]}};

function Ring({v,s=40,w=3}){const[a,sA]=useState(0);const r=(s-w)/2,ci=2*Math.PI*r;useEffect(()=>{const t=setTimeout(()=>sA(v),80);return()=>clearTimeout(t)},[v]);return(<div style={{position:"relative",width:s,height:s}}><svg width={s} height={s} style={{transform:"rotate(-90deg)"}}><circle cx={s/2} cy={s/2} r={r} fill="none" stroke={C.bd} strokeWidth={w}/><circle cx={s/2} cy={s/2} r={r} fill="none" stroke={hc(v)} strokeWidth={w} strokeDasharray={ci} strokeDashoffset={ci-ci*a/100} strokeLinecap="round" style={{transition:"stroke-dashoffset 1s cubic-bezier(.4,0,.2,1)"}}/></svg><div style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",fontSize:s*.25,fontWeight:800,color:hc(v)}}>{v}</div></div>)}
function Spark({data,color,w=48,h=16}){if(!data||data.length<2)return null;const mn=Math.min(...data),mx=Math.max(...data),rng=mx-mn||1;const pts=data.map((v,i)=>`${(i/(data.length-1))*w},${h-((v-mn)/rng)*h}`).join(" ");return(<svg width={w} height={h} style={{overflow:"visible"}}><polyline points={pts} fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round"/><circle cx={w} cy={h-((data[data.length-1]-mn)/rng)*h} r="2" fill={color}/></svg>)}
function XPBar({xp}){const lv=gLv(xp);const pct=lv.nx?Math.round(((xp-lv.m)/(lv.nx.m-lv.m))*100):100;return(<div><div style={{display:"flex",justifyContent:"space-between",marginBottom:2}}><span style={{fontSize:9,fontWeight:700,color:lv.c}}>{lv.i} {lv.n}</span><span style={{fontSize:8,color:C.dm}}>{xp.toLocaleString()} XP</span></div><div style={{height:3,background:C.bd,borderRadius:2}}><div style={{height:"100%",width:`${pct}%`,background:G,borderRadius:2,transition:"width 1s ease"}}/></div></div>)}

function UploadPage({onData,onDemo}){const[parsing,setP]=useState(false);const[result,setR]=useState(null);const[err,setE]=useState(null);const ref=useRef(null);
const handle=async f=>{if(!f)return;setP(true);setE(null);try{const r=await parseCSV(f);setR(r)}catch(e){setE(e.message)}setP(false)};
const confirm=()=>{if(!result)return;const{projects,pms}=transformToProjects(result.rows,result.mapping);saveProjects(projects);savePMs(pms);onData()};
return(<div style={{minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:32}}>
<div style={{marginBottom:40,textAlign:"center"}}><div style={{width:64,height:64,borderRadius:18,background:G,display:"flex",alignItems:"center",justifyContent:"center",fontSize:32,fontWeight:900,color:"#fff",margin:"0 auto 16px",boxShadow:`0 8px 32px ${C.ac}30`}}>D</div><div style={{fontSize:28,fontWeight:800,color:C.tx}}>DeliverIQ</div><div style={{fontSize:10,fontWeight:700,letterSpacing:2.5,textTransform:"uppercase",color:C.ac,marginTop:4}}>Delivery Intelligence</div></div>
{!result?(<div style={{width:"100%",maxWidth:500}}>
<div onClick={()=>ref.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();handle(e.dataTransfer.files[0])}} style={{border:`2px dashed ${C.bh}`,borderRadius:20,padding:"48px 32px",textAlign:"center",cursor:"pointer",background:C.sf}}>
<input ref={ref} type="file" accept=".csv,.tsv" style={{display:"none"}} onChange={e=>handle(e.target.files[0])}/>
{parsing?(<div><div style={{fontSize:40,marginBottom:12,animation:"spin 1.5s linear infinite"}}>🔄</div><div style={{fontSize:16,fontWeight:700,color:C.tx}}>Parsing...</div></div>)
:(<div><div style={{fontSize:48,marginBottom:16}}>📄</div><div style={{fontSize:18,fontWeight:700,color:C.tx,marginBottom:8}}>Drop your CSV here</div><div style={{fontSize:13,color:C.sb}}>or click to browse</div></div>)}</div>
{err&&<div style={{marginTop:16,padding:16,background:`${C.rd}10`,border:`1px solid ${C.rd}30`,borderRadius:12,color:C.rd}}>❌ {err}</div>}
<div style={{textAlign:"center",marginTop:24}}><div style={{fontSize:12,color:C.dm,marginBottom:8}}>or</div><button onClick={onDemo} style={{padding:"12px 28px",borderRadius:12,border:`1.5px solid ${C.bh}`,background:"transparent",color:C.sb,fontSize:14,fontWeight:600,cursor:"pointer"}}>🎮 Try Demo Mode</button></div>
</div>)
:(<div style={{width:"100%",maxWidth:700}}><div style={{background:C.sf,borderRadius:16,padding:24,border:`1px solid ${C.bd}`}}>
<div style={{fontSize:18,fontWeight:700,color:C.tx,marginBottom:4}}>Column Mapping</div><div style={{fontSize:12,color:C.sb,marginBottom:16}}>{result.rowCount} rows · {result.headers.length} columns</div>
<table style={{width:"100%",borderCollapse:"collapse",marginBottom:16}}><thead><tr style={{borderBottom:`1px solid ${C.bd}`}}>{["Column","→","Maps To","Sample","Conf"].map((h,i)=><th key={i} style={{padding:"6px 10px",textAlign:"left",fontSize:9,fontWeight:700,letterSpacing:1,textTransform:"uppercase",color:C.dm}}>{h}</th>)}</tr></thead>
<tbody>{result.headers.map((h,i)=>{const m=result.mapping[h];return(<tr key={i} style={{borderBottom:`1px solid ${C.bd}06`}}><td style={{padding:"6px 10px"}}><span style={{fontSize:10,fontFamily:"monospace",fontWeight:600,color:C.tx,background:C.bg,padding:"1px 5px",borderRadius:3}}>{h}</span></td><td style={{padding:"6px 10px",color:C.dm}}>→</td><td style={{padding:"6px 10px"}}><select value={m.field} onChange={e=>{const nm={...result.mapping};nm[h]={...m,field:e.target.value,confidence:100};setR({...result,mapping:nm})}} style={{background:C.bg,border:`1px solid ${C.bd}`,borderRadius:5,padding:"3px 6px",color:C.tx,fontSize:10}}><option value="unmapped">— Skip —</option>{["project_ref","project_name","client","milestone_name","milestone_no","milestone_value","milestone_status","expected_date","actual_date","pm","region","health","overdue","csat","consultant"].map(f=><option key={f} value={f}>{f.replace(/_/g," ")}</option>)}</select></td><td style={{padding:"6px 10px",fontSize:9,color:C.sb,fontFamily:"monospace",maxWidth:100,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{result.preview[0]?.[h]||"—"}</td><td style={{padding:"6px 10px"}}><span style={{fontSize:8,fontWeight:700,color:m.confidence>=85?C.gn:C.am,background:(m.confidence>=85?C.gn:C.am)+"18",padding:"1px 5px",borderRadius:3}}>{m.confidence}%</span></td></tr>)})}</tbody></table>
<div style={{display:"flex",justifyContent:"space-between"}}><button onClick={()=>setR(null)} style={{padding:"8px 18px",borderRadius:8,border:`1px solid ${C.bd}`,background:"transparent",color:C.sb,fontSize:12,fontWeight:600,cursor:"pointer"}}>← Back</button><button onClick={confirm} style={{padding:"8px 24px",borderRadius:8,border:"none",background:G,color:"#fff",fontSize:13,fontWeight:700,cursor:"pointer"}}>✓ Build Dashboard</button></div>
</div></div>)}</div>)}

function Dash({P,pms,onReup}){const[view,sV]=useState("portfolio");const[selP,sP]=useState(null);const[fl,sFl]=useState("all");const[rptOpen,setRpt]=useState(false);const[rptColor,setRptColor]=useState("#3B82F6");const[orgName,setOrgName]=useState("DeliverIQ");
const COLOR_PRESETS=[{n:"Blue",p:"#3B82F6",s:"#8B5CF6"},{n:"Emerald",p:"#059669",s:"#10B981"},{n:"Purple",p:"#7C3AED",s:"#A78BFA"},{n:"Amber",p:"#D97706",s:"#F59E0B"},{n:"Rose",p:"#E11D48",s:"#FB7185"},{n:"Slate",p:"#475569",s:"#64748B"}];
const secFor=hex=>{const m=COLOR_PRESETS.find(c=>c.p.toLowerCase()===hex.toLowerCase());return m?m.s:hex};
const runReport=()=>{generateReport({projects:P,pms,orgName:orgName||"DeliverIQ",theme:{primary:rptColor,secondary:secFor(rptColor)}});setRpt(false)};
const fd=fl==="all"?P:P.filter(p=>p.status===fl);const tR=P.reduce((s,p)=>s+p.rev,0),tB=P.reduce((s,p)=>s+p.billed,0),rR=P.filter(p=>p.status!=="on-track").reduce((s,p)=>s+(p.rev-p.billed),0),aH=P.length?Math.round(P.reduce((s,p)=>s+p.health,0)/P.length):0,oT=P.reduce((s,p)=>s+p.ov,0);
const cn={all:P.length,"on-track":P.filter(p=>p.status==="on-track").length,"at-risk":P.filter(p=>p.status==="at-risk").length,critical:P.filter(p=>p.status==="critical").length};
const grads=["linear-gradient(135deg,#10B981,#059669)","linear-gradient(135deg,#3B82F6,#2563EB)","linear-gradient(135deg,#8B5CF6,#7C3AED)","linear-gradient(135deg,#F59E0B,#D97706)","linear-gradient(135deg,#EF4444,#DC2626)"];
return(<div style={{minHeight:"100vh"}}><div style={{position:"sticky",top:0,zIndex:50,background:"rgba(8,14,26,.9)",backdropFilter:"blur(16px)",borderBottom:`1px solid ${C.bd}`,padding:"0 24px",display:"flex",alignItems:"center",justifyContent:"space-between",height:52}}>
<div style={{display:"flex",alignItems:"center",gap:16}}><div style={{display:"flex",alignItems:"center",gap:7}}><div style={{width:28,height:28,borderRadius:7,background:G,display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,fontWeight:900,color:"#fff"}}>D</div><div><div style={{fontSize:13,fontWeight:800,color:C.tx,lineHeight:1}}>DeliverIQ</div><div style={{fontSize:6,fontWeight:700,letterSpacing:2,textTransform:"uppercase",color:C.ac,marginTop:1}}>Delivery Intelligence</div></div></div>
<div style={{display:"flex",gap:1,background:C.sf,borderRadius:8,padding:2}}>{[{id:"portfolio",l:"Portfolio",i:"⬡"},{id:"pms",l:"PMs",i:"◉"}].map(n=><button key={n.id} onClick={()=>sV(n.id)} style={{padding:"6px 14px",borderRadius:6,border:"none",cursor:"pointer",fontSize:11,fontWeight:600,background:view===n.id?C.bd:"transparent",color:view===n.id?C.tx:C.dm}}><span style={{marginRight:4,opacity:view===n.id?1:.5}}>{n.i}</span>{n.l}</button>)}</div></div>
<div style={{display:"flex",gap:8,alignItems:"center"}}><span style={{display:"inline-flex",alignItems:"center",gap:4,fontSize:10,fontWeight:600,color:C.gn}}><span style={{width:6,height:6,borderRadius:3,background:C.gn,animation:"pulse 2s infinite"}}/>{P.length} projects</span><button onClick={()=>setRpt(true)} style={{padding:"5px 14px",borderRadius:6,border:"none",background:G,color:"#fff",fontSize:10,fontWeight:700,cursor:"pointer"}}>📄 Board Report</button><button onClick={onReup} style={{padding:"5px 12px",borderRadius:6,border:`1px solid ${C.bd}`,background:"transparent",color:C.sb,fontSize:10,fontWeight:600,cursor:"pointer"}}>↻ Re-upload</button></div></div>
<div style={{padding:"20px 24px",maxWidth:1200,margin:"0 auto"}}>
{view==="portfolio"&&<div><div style={{fontSize:20,fontWeight:800,color:C.tx,marginBottom:16}}>Portfolio Overview</div>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,marginBottom:20}}>{[{i:"💰",l:"Portfolio",v:fmt(tR),sub:`${tR>0?Math.round(tB/tR*100):0}% billed`,c:C.tx},{i:"🔥",l:"At Risk",v:fmt(rR),sub:`${cn["at-risk"]+cn.critical} projects`,c:C.rd},{i:"💚",l:"Health",v:`${aH}%`,sub:`${cn["on-track"]} on track`,c:hc(aH)},{i:"⏰",l:"Overdue",v:`${oT}`,sub:"milestones",c:oT>0?C.rd:C.gn}].map((k,i)=><div key={i} style={{background:`linear-gradient(135deg,${C.sf},${C.cd})`,border:`1px solid ${C.bd}`,borderRadius:12,padding:"16px 18px",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:-6,right:-2,fontSize:38,opacity:.06}}>{k.i}</div><div style={{fontSize:8,fontWeight:700,letterSpacing:1.2,textTransform:"uppercase",color:C.dm,marginBottom:6}}>{k.l}</div><div style={{fontSize:26,fontWeight:800,color:k.c}}>{k.v}</div><div style={{fontSize:9,color:C.sb,marginTop:4}}>{k.sub}</div></div>)}</div>
<div style={{display:"flex",gap:5,marginBottom:14}}>{[{k:"all",l:"All"},{k:"on-track",l:"On Track",c:C.gn},{k:"at-risk",l:"At Risk",c:C.am},{k:"critical",l:"Critical",c:C.rd}].map(f=><button key={f.k} onClick={()=>sFl(f.k)} style={{padding:"5px 12px",borderRadius:16,border:`1.5px solid ${fl===f.k?(f.c||C.ac):C.bd}`,background:fl===f.k?(f.c||C.ac)+"15":"transparent",color:fl===f.k?(f.c||C.ac):C.sb,fontSize:10,fontWeight:600,cursor:"pointer",display:"flex",gap:4,alignItems:"center"}}>{f.l}<span style={{background:fl===f.k?(f.c||C.ac)+"25":C.bd,padding:"0 5px",borderRadius:7,fontSize:9,fontWeight:700}}>{cn[f.k]}</span></button>)}</div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(280px,1fr))",gap:10}}>{fd.sort((a,b)=>a.health-b.health).map(p=>{const bp=p.rev>0?Math.round(p.billed/p.rev*100):0;return(<div key={p.id} onClick={()=>sP(p)} style={{background:C.sf,border:`1px solid ${p.status==="critical"?C.rd+"40":C.bd}`,borderRadius:12,padding:14,cursor:"pointer",transition:"all .2s"}} onMouseOver={e=>{e.currentTarget.style.transform="translateY(-2px)";e.currentTarget.style.boxShadow="0 8px 20px rgba(0,0,0,.3)"}} onMouseOut={e=>{e.currentTarget.style.transform="";e.currentTarget.style.boxShadow="none"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:10}}><div style={{flex:1,minWidth:0}}><div style={{fontSize:12,fontWeight:700,color:C.tx,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{p.name}</div><div style={{fontSize:9,color:C.sb,marginTop:1}}>{p.client} · {p.region}</div></div><Ring v={p.health} s={38} w={2.5}/></div><div style={{display:"flex",gap:12,marginBottom:10}}><div><div style={{fontSize:7,fontWeight:600,letterSpacing:.8,textTransform:"uppercase",color:C.dm}}>Value</div><div style={{fontSize:12,fontWeight:700,color:C.tx}}>{fmt(p.rev)}</div></div><div><div style={{fontSize:7,fontWeight:600,letterSpacing:.8,textTransform:"uppercase",color:C.dm}}>Billed</div><div style={{fontSize:12,fontWeight:700,color:bp>70?C.gn:bp>30?C.am:C.rd}}>{bp}%</div></div>{p.trend&&<div><div style={{fontSize:7,fontWeight:600,letterSpacing:.8,textTransform:"uppercase",color:C.dm}}>Trend</div><Spark data={p.trend} color={p.trend[4]>=0?C.gn:C.rd} w={40} h={14}/></div>}</div><div style={{height:2,background:C.bd,borderRadius:1,marginBottom:8}}><div style={{height:"100%",width:`${bp}%`,background:`linear-gradient(90deg,${bp>70?C.gn:bp>30?C.am:C.rd},${C.ac})`,borderRadius:1}}/></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:9,color:C.sb}}><b style={{color:C.tx}}>{p.cms}</b>/{p.ms} ms · {p.pm}</span>{p.ov>0?<span style={{fontSize:8,fontWeight:700,color:C.rd,background:`${C.rd}12`,padding:"1px 6px",borderRadius:4}}>{p.ov} overdue</span>:<span style={{fontSize:8,color:C.gn,fontWeight:600}}>✓</span>}</div></div>)})}</div></div>}
{view==="pms"&&<div><div style={{fontSize:20,fontWeight:800,color:C.tx,marginBottom:16}}>PM Performance</div><div style={{display:"flex",flexDirection:"column",gap:8}}>{pms.map((pm,i)=>{const lv=gLv(pm.xp);const pp=P.filter(p=>p.pm===pm.name);return(<div key={i} style={{background:i===0?`linear-gradient(135deg,${C.sf},${C.gn}08)`:C.sf,border:`1px solid ${i===0?C.gn+"30":C.bd}`,borderRadius:12,padding:"14px 18px"}}><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{fontSize:20,width:28,textAlign:"center"}}>{["🥇","🥈","🥉"][i]||<span style={{fontSize:13,color:C.dm,fontWeight:700}}>#{i+1}</span>}</div><div style={{width:40,height:40,borderRadius:20,background:grads[i%5],display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:800,color:"#fff",position:"relative"}}>{pm.ini}<div style={{position:"absolute",bottom:-3,right:-3,fontSize:10,background:C.sf,borderRadius:5,padding:"0 2px",border:`1px solid ${C.bd}`}}>{lv.i}</div></div><div style={{flex:1,minWidth:0}}><div style={{display:"flex",alignItems:"center",gap:5}}><span style={{fontSize:13,fontWeight:700,color:C.tx}}>{pm.name}</span><span style={{fontSize:9,color:C.dm}}>{pm.region}</span>{pm.streak>0&&<span style={{fontSize:8,fontWeight:700,color:C.am}}>🔥{pm.streak}w</span>}<span style={{fontSize:8,fontWeight:600,color:lv.c}}>{lv.n}</span></div><div style={{marginTop:4,maxWidth:180}}><XPBar xp={pm.xp}/></div><div style={{display:"flex",gap:3,marginTop:4}}>{pp.map(proj=><button key={proj.id} onClick={()=>sP(proj)} style={{padding:"1px 7px",borderRadius:4,border:`1px solid ${sc(proj.status)}30`,background:`${sc(proj.status)}10`,color:sc(proj.status),fontSize:8,fontWeight:600,cursor:"pointer"}}>{proj.name.length>14?proj.name.slice(0,14)+"…":proj.name}</button>)}</div></div><div style={{display:"flex",gap:4}}>{(pm.badges||[]).map((bk,j)=>{const b=BADGES[bk];return b?<span key={j} style={{width:24,height:24,borderRadius:6,background:C.sf,border:`1px solid ${C.bh}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:11}} title={b.n}>{b.i}</span>:null})}</div><div style={{display:"flex",gap:14,flexShrink:0}}><div style={{textAlign:"center"}}><div style={{fontSize:7,fontWeight:600,color:C.dm,marginBottom:2}}>Health</div><Ring v={Math.round(pm.ah)} s={34} w={2.5}/></div><div style={{textAlign:"center"}}><div style={{fontSize:7,fontWeight:600,color:C.dm,marginBottom:2}}>Billing</div><div style={{fontSize:15,fontWeight:800,color:pm.br>=.7?C.gn:pm.br>=.4?C.am:C.rd}}>{Math.round(pm.br*100)}%</div></div></div></div>{pm.ah<50&&<div style={{marginTop:8,marginLeft:80,padding:"5px 10px",background:`${C.rd}06`,border:`1px solid ${C.rd}15`,borderRadius:6,fontSize:10,color:"#F87171",borderLeft:`3px solid ${C.rd}`}}>⚡ Coaching recommended</div>}</div>)})}</div></div>}
</div>
{rptOpen&&<div onClick={()=>setRpt(false)} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.6)",zIndex:110,display:"flex",alignItems:"center",justifyContent:"center",backdropFilter:"blur(4px)"}}><div onClick={e=>e.stopPropagation()} style={{width:420,maxWidth:"92vw",background:"#0B1120",border:`1px solid ${C.bd}`,borderRadius:16,padding:24,animation:"fadeUp .3s ease"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><div style={{fontSize:17,fontWeight:800,color:C.tx}}>📄 Board Report</div><button onClick={()=>setRpt(false)} style={{background:C.bd,border:"none",borderRadius:7,width:30,height:30,color:C.sb,fontSize:14,cursor:"pointer"}}>✕</button></div>
<div style={{fontSize:12,color:C.sb,marginBottom:20}}>Customize before generating. Opens a print-ready report — click "Save as PDF".</div>
<div style={{fontSize:10,fontWeight:600,letterSpacing:.8,textTransform:"uppercase",color:C.dm,marginBottom:8}}>Organization Name</div>
<input value={orgName} onChange={e=>setOrgName(e.target.value)} style={{width:"100%",padding:"10px 14px",borderRadius:8,border:`1px solid ${C.bh}`,background:C.bg,color:C.tx,fontSize:14,fontWeight:600,marginBottom:18}}/>
<div style={{fontSize:10,fontWeight:600,letterSpacing:.8,textTransform:"uppercase",color:C.dm,marginBottom:8}}>Brand Color</div>
<div style={{display:"grid",gridTemplateColumns:"repeat(6,1fr)",gap:8,marginBottom:14}}>{COLOR_PRESETS.map(c=><button key={c.n} onClick={()=>setRptColor(c.p)} title={c.n} style={{height:44,borderRadius:10,border:`2px solid ${rptColor.toLowerCase()===c.p.toLowerCase()?"#fff":"transparent"}`,background:`linear-gradient(135deg,${c.p},${c.s})`,cursor:"pointer",boxShadow:rptColor.toLowerCase()===c.p.toLowerCase()?`0 0 0 2px ${c.p}`:"none"}}/>)}</div>
<div style={{display:"flex",alignItems:"center",gap:10,marginBottom:22}}><span style={{fontSize:11,color:C.sb}}>Custom:</span><input type="color" value={rptColor} onChange={e=>setRptColor(e.target.value)} style={{width:40,height:32,border:"none",borderRadius:8,cursor:"pointer",background:"transparent"}}/><input value={rptColor} onChange={e=>{if(/^#[0-9A-Fa-f]{6}$/.test(e.target.value))setRptColor(e.target.value)}} maxLength={7} style={{width:90,padding:"6px 10px",borderRadius:7,border:`1px solid ${C.bh}`,background:C.bg,color:C.tx,fontSize:12,fontFamily:"monospace",fontWeight:600}}/></div>
<button onClick={runReport} style={{width:"100%",padding:"13px 0",borderRadius:10,border:"none",background:`linear-gradient(135deg,${rptColor},${secFor(rptColor)})`,color:"#fff",fontSize:14,fontWeight:700,cursor:"pointer"}}>Generate Report →</button>
</div></div>}
{selP&&<div onClick={()=>sP(null)} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.6)",zIndex:100,display:"flex",justifyContent:"flex-end",backdropFilter:"blur(4px)"}}><div onClick={e=>e.stopPropagation()} style={{width:380,maxWidth:"90vw",height:"100%",background:"#0B1120",borderLeft:`1px solid ${C.bd}`,padding:"22px 18px",overflowY:"auto",animation:"fadeUp .3s ease"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><div><div style={{fontSize:9,fontWeight:700,letterSpacing:1.5,textTransform:"uppercase",color:sc(selP.status)}}>{selP.status==="on-track"?"● ON TRACK":selP.status==="at-risk"?"▲ AT RISK":"◆ CRITICAL"}</div><div style={{fontSize:17,fontWeight:800,color:C.tx,marginTop:2}}>{selP.name}</div><div style={{fontSize:11,color:C.sb,marginTop:2}}>{selP.client} · {selP.region} · PM: {selP.pm}</div></div><button onClick={()=>sP(null)} style={{background:C.bd,border:"none",borderRadius:7,width:30,height:30,color:C.sb,fontSize:14,cursor:"pointer"}}>✕</button></div><div style={{display:"flex",gap:14,alignItems:"center",padding:"14px 0",borderTop:`1px solid ${C.bd}`,borderBottom:`1px solid ${C.bd}`,marginBottom:14}}><Ring v={selP.health} s={70} w={5}/><div><div style={{fontSize:22,fontWeight:800,color:C.tx}}>{fmt(selP.rev)}</div><div style={{fontSize:11,color:C.sb}}>{selP.rev>0?Math.round(selP.billed/selP.rev*100):0}% billed · {selP.cms}/{selP.ms} ms</div></div></div>{selP.ov>0&&<div style={{background:`${C.rd}08`,border:`1px solid ${C.rd}20`,borderRadius:9,padding:12,marginBottom:10}}><div style={{fontSize:12,fontWeight:700,color:C.rd}}>⚡ {selP.ov} overdue · {selP.dd}d behind</div></div>}<div style={{background:C.sf,borderRadius:9,padding:12,border:`1px solid ${C.bd}`,marginBottom:10}}><div style={{fontSize:9,fontWeight:600,letterSpacing:.8,textTransform:"uppercase",color:C.dm,marginBottom:4}}>Next: {selP.nm}</div><div style={{fontSize:11,color:C.sb}}>Due {selP.nd}</div></div></div></div>}
</div>)}

export default function App(){const[mode,setMode]=useState(()=>hasData()?"dash":"upload");const[data,setData]=useState(()=>loadAll());
return mode==="upload"?(<UploadPage onData={()=>{setData(loadAll());setMode("dash")}} onDemo={()=>{saveProjects(SAMPLE_PROJECTS);savePMs(SAMPLE_PMS);setData({projects:SAMPLE_PROJECTS,pms:SAMPLE_PMS});setMode("dash")}}/>)
:(<Dash P={data.projects||[]} pms={data.pms||[]} onReup={()=>{clearAll();setMode("upload")}}/>)}
